#!/bin/bash
set -e

create_cert() {

	if [ ! -d ${SSL_ROOT} ]; then
	mkdir -p ${SSL_ROOT}
	else
	if [ -a ${SSL_ROOT}/server.key ]; then
	echo "found exsisting server key"
	else
	openssl genrsa -out ${SSL_ROOT}/server.key 4096
	openssl req -subj "/CN=${HOST_NAME}/C=AT" -new -key ${SSL_ROOT}/server.key -out ${SSL_ROOT}/server.csr
	openssl x509 -req -days 365 -in ${SSL_ROOT}/server.csr -signkey ${SSL_ROOT}/server.key -out ${SSL_ROOT}/server.crt
	chmod 400 ${SSL_ROOT}/server.key
	fi
	fi
	a2enmod ssl

}

# Download and install owncloud
case "$@" in
    start)
	
	create_cert
	if [ -d ${WWW_ROOT}/owncloud/data ]; then
	echo "found exsisting data-volume"
	else
        echo "downloading and installing owncloud..."
	wget --no-check-certificate https://download.owncloud.org/community/${OC_VERS}.zip
	unzip ${OC_VERS}.zip
	rm -f ${OC_VERS}.zip
	mkdir -p ${WWW_ROOT}/owncloud/data
	chown -R www-data:www-data ${WWW_ROOT}/owncloud/data
	fi
	exec ${APACHE_BIN} "-D FOREGROUND" &
	exec "/bin/bash"
	child=$!
        wait $child

    ;;
    cert)
	create_cert
    ;;
    shell)
        exec "/bin/bash"
    ;;
esac
